language: node_js
sudo: false
dist: trusty
node_js:
  - "7"

addons:
    chrome: stable

env:
  global:
    - workingDir=$(pwd)  

jobs:
    include:
      - stage: Verify
        script: "ng build --prod && npm run sw"

      - stage: Test
        env: MODE=unit TEST=karma
      - stage: Test
        env: MODE=e2e_cits TEST=smoke
      - stage: Test
        env: MODE=e2e_cits TEST=layout

      - stage: Deploy
        script: skip
        env: "DEPLOY_MODE=heroku-native"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g @angular/cli@latest    
    - npm install -g http-server
      # source the env.sh script to get exported variables
    - source ./scripts/ci/env.sh print
    - curl -sL https://raw.githubusercontent.com/x0156/cits-travis-seed/x0156/install.sh | bash
    - . ./sourcefile

install:
    - npm install

before_script:  
  - "echo 'echo $*;exit 1;' > fail;chmod u+x fail;"
  - chmod -R +x ./scripts/ci
 
script:
  - ./scripts/ci/travis-script.sh

cache:
    directories:
        - $HOME/.npm
